apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: echo-telegram-bot
  name: echo-telegram-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-telegram-bot
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: echo-telegram-bot
    spec:
      containers:
      - image: okteto/python:3
        name: echo-telegram-bot
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
